export const Translator = {
  frequency: {'pl': 'Częstotliwość', 'en': 'Frequency'},
  externalForces: {'pl': 'Siły zewnętrzne', 'en': 'External forces'},
  linearExaggeration: {'pl': 'Logarytmiczne uwypuklenie deformacji', 'en': 'Logarythmic deformation exagerration'},
  strain: {'pl': 'Naprężenie', 'en': 'Strain'},
  timeExpansion: {'pl': 'Logarytmiczne spowolnienie czasu', 'en': 'Logarythmic time expansion'},
  voltageInput: {'pl': 'Napięcie wejściowe', 'en': 'Voltage Input'},
  time: {'pl': 'Czas', 'en': 'Time'},
  harmonicNumber: {'pl': 'Liczba harmoniczna', 'en': 'Harmonic number'},
  voltageOutput: {'pl': 'Napięcie wyjściowe', 'en': 'Voltage output'},
  stretch: {'pl': 'Liniowe rozciągnięcie', 'en': 'Stretch'},
  dampingMass: {'pl': 'Masa tłumiąca', 'en': 'Damping mass'},
  mechanicalDampingCoefficient: {'pl': 'Współczynnik tłumienia mechanicznego', 'en': 'Mechanic damping coefficient'},
  internalFrequency: {'pl': 'Częstotliwość własna', 'en': 'Internal frequency'},
  amplitude: {'pl': 'Amplituda', 'en': 'Amplitude'},
  powerOutput: {'pl': 'Moc wyjściowa', 'en': 'Power output'},
  maxPowerOutput: {'pl': 'Maksymalna moc wyjściowa', 'en': 'Max power output'},
  substrateThickness: {'pl': 'Grubość podłoża', 'en': 'Substrate thickness'},
  receiverResistance: {'pl': 'Opór odbiornika', 'en': 'Receiver resistance'},
  simulationMode: {'pl': 'Tryb symulacji', 'en': 'Simulation mode'},
  chooseMaterial: {'pl': 'Wybierz materiał', 'en': 'Choose material'},
  plateAxis: {'pl': 'Oś płyty', 'en': 'Plate axis'},
  plateResolution: {'pl': 'Rozdzielczość płyty w osi', 'en': 'Plate resolution'},
  view: {'pl': 'Przeglądaj', 'en': 'View'},
  edit: {'pl': 'Edytuj', 'en': 'Edit'},
  crystal: {'pl': 'Kryształ', 'en': 'Crystal'},
  ceramic_tp: {'pl': 'Ceramiczny', 'en': 'Ceramic'},
  ceramic_lp: {'pl': 'Ceramiczny, spolaryzowany w osi długości', 'en': 'Ceramic, longitude poling'},
  name: {'pl': 'Nazwa', 'en': 'Name'},
  type: {'pl': 'Type', 'en': 'Type'},
  Quartz: {'pl': 'Kwarc', 'en': 'Quartz'},
  Langasite: {'pl': 'Langazyt', 'en': 'Langasite'},
  'Barium titanate': {'pl': 'Tytanek Baru', 'en': 'Barium titanate'},
  'Lead Zirconate Titanate - 4': {'pl': 'Tytanian-cyrkonian ołowiu - 4', 'en': 'Lead Zirconate Titanate - 4'},
  'Lead Zirconate Titanate - 5A': {'pl': 'Tytanian-cyrkonian ołowiu - 5A', 'en': 'Lead Zirconate Titanate - 5A'},
  'Lead Zirconate Titanate - 5H': {'pl': 'Tytanian-cyrkonian ołowiu - 5H', 'en': 'Lead Zirconate Titanate - 5H'},
  'Lead Zirconate Titanate - 8': {'pl': 'Tytanian-cyrkonian ołowiu - 8', 'en': 'Lead Zirconate Titanate - 8'},
  density: {'pl': 'Gęstość', 'en': 'Density'},
  dissipationFactor: {'pl': 'Współczynnik rozporszenia', 'en': 'Dissipation factor'},
  poisonRatio: {'pl': 'Współczynnik Poissona', 'en': 'Poisson\'s ratio'},
  mechQ: {'pl': 'Mechaniczny współczynnik Q', 'en': 'Mechanical Q factor'},
  c: {'pl': 'Współczynnik c', 'en': 'C factor'},
  e: {'pl': 'Współczynnik e', 'en': 'E factor'},
  epsilon_fact: {'pl': 'Współczynnik epsilon', 'en': 'Epsilon factor'},
  youngModulus: {'pl': 'Moduł Younga', 'en': 'Young modulus'}, /*
  Langasite: {'pl': 'Langazyt', 'en': 'Langasite'},
  Langasite: {'pl': 'Langazyt', 'en': 'Langasite'},
  */
}

// {'pl': '', 'en': ''}
